### ISSUE TITLE
what is the difference between categories , ids, category_id, and image_id?

### ISSUE THREAD

**Issue by isalirezag** [cocodataset/cocoapi#187]
I am, working with the coco api and when i print len(ategories) it shows 80, but when i print them i see we have 90 id...

![image](https://user-images.githubusercontent.com/12434910/42053480-aaaca0aa-7adf-11e8-97a3-f9849b868aca.png)
.
.
.
![image](https://user-images.githubusercontent.com/12434910/42053569-d8f39f7c-7adf-11e8-80ef-4ed01a22025a.png)

**what is the differentce between category and id?
also what is the difference between image_id and id?
and finally what is the difference between id and category_id?**

**Comment by isalirezag** [comment]
I am not sure if it is a bug or if it is design in this way on purpose, but the ids does not increases step by step. there is a jump between them sometimes.

Why is that so?

**Comment by netanel-s** [comment]
I think this is because they added categories (80->91), so that they use the indexing of the newer set, also if you use the previous set for index compatibility.

**Comment by tanjiarui** [comment]
I recommend admin to set up a notice about this gap so that testers can bypass this pitfall when they run the evalDemo! @pdollar

**Comment by KingofAsianPopJC** [comment]
'category_id' stands for which type this object is classified to, the length of it is 80;

'image_id' stands for which specific image this object belong to, the lenght of it is the lenght of all images (about 82783: for coco2014train)

'id' stands for the individual annotation object, because one single image may contain several annotations, the length of it may be the length of key 'annoatation' (I'm not sure and i'm not clear about the how is the 'id'  named because it is not named step by step)

**Comment by jediofgever** [comment]
@KingofAsianPopJC  so `category_id` is basically the class of that object ?

**Comment by TNemes-3141** [comment]
@jediofgever Yes, it is.

**Comment by isalirezag** [comment]
`categories` are the classes that you have
each category has a specific `category_id` which can be thought of the class id
