### ISSUE TITLE
COCOEval: Effect and purpose of Maximum Detections unclear

### ISSUE THREAD

**Issue by mincowski** [cocodataset/cocoapi#222]
In the COCOEval class of the Python API, the effect of the maximum detections parameter is quite unclear to me.

Reading across the internet, the precision-recall curves should be created by adjusting the score threshold for accepted detections and then calculate the precision and recall for the resulting detected set. I don’t see where this is happening in the `COCOEval` class. To me, it seems that the code calculates the curve from the `maxDets` highest scoring elements. So for the default parameters, it consists of 3 points (`maxDets = 1, 10, 100`) Is that correct and if so, why is the equivalent to the first method?

Especially, I tried to use the ground-truth boxes as input for the ground-truth and the detected images, so I expect the evaluation to return average precision = 1 and average recall = 1.
If the total number of boxes is less than the number of maximum detections (100), this is true. But if I take more boxes (> 100), average precision and recall drop.
While I could understand this behavior for the recall (not all detections are taken into account so not everything is detected), in my opinion this doesn’t make sense for the average precision.

If I feed the ground-truth boxes into the detections, shouldn’t I always get average precision = 1?

**Comment by mincowski** [comment]
I came to the conclusion, that this is just the way the cocoapi defines its metric. So I could just define my own, slightly different metric which is fine as well.

**Comment by kdh4672** [comment]
I was confused because i didn't know what maxDets for, but i solved by your note. thank you.
For check, so if I set maxdets as 1, and detect more than 1, it is fail,  so recall will decrease.
Is it correct?

**Comment by dinis-rodrigues** [comment]
I'm having the same difficulty in understanding this topic, but I'm going to leave a quote of what I've found [here](https://stackoverflow.com/questions/52068835/tensorboard-graph-recall)

> I think "AR@10" means it's taking the 10 highest confidence predictions, across classes, for a single image and calculating metrics on just those 10 detections. Obviously recall will be hurt if there are 20 objects in the image, since max recall is now 0.5.

My take on this, is that for AR@1 it should just consider 1 detection and check if there is a match with respective ground truth, discarding every other ground truth. But is seems it considers all the other ground truths as False Negatives which dramatically lowers the metric (this makes no sense to me).

I'm trying to understand this by reading the code, but it's not that readable..
And if this is the case, why is the metric relevant? I can't seem to find any reference on this metric in any published paper.

**Comment by rizavelioglu** [comment]
_Finally_, I figured out what the `maxDets` argument is doing (I believe).
Here's the evaluation results (`COCOeval`'s "evalImgs" attribute) for an example image:
![maxDets=100](https://github.com/cocodataset/cocoapi/assets/40141130/d447d409-6202-4ff3-b3aa-e0a409103ed5)
So, for this single image (`image_id=28`), we have:
- only 1 Ground-Truth (highlighted row) -> `gtId=28` (because all `gtId`'s appear in the `gtIds` attribute for every image),
- multiple detections for `category_id=23` (which is the correct object appearing in the image)
- many wrong detections (false positives) for other `category_id`'s: they are wrong because they did not 'match' with the ground-truth, as shown with blank list in the `gtIds` attribute & blank lists in `dtMatches` and `gtMatches` attributes.

Further observations;
- In the highlighted row we can see that only 1 out of 6 detections matched the ground-truth as can be seen in the `gtMatches` attribute: the one with `dtId=17144`. This is because the other 5 detections did not pass the IoU threshold. They would have appeared in `gtMatches` if they had passed it. Hence, 1 True Positive and 5 more False Positives (assuming IoU=0.50).
- In addition, you can see in the `maxDet` attribute that it is set to `100`.

---
Next, we see the evaluation results for the same image with the same setting except this time the `maxDet` is set to `1` with `cocoEval.params.maxDets = [1]`:
![maxDets=1](https://github.com/cocodataset/cocoapi/assets/40141130/1a58cb6b-9e09-487e-be13-bcb506219501)
The only difference is in the highlighted row: the detections are filtered and the one with the highest score `dtScores` is kept.
**So the take from this is**: contrary to the belief that `maxDet` takes the top-`maxDet` detections with the highest score for an image, it takes the top-`maxDet` detections **per class** for an image. 
Perhaps the authors tried to tell that [on the official website](https://cocodataset.org/#detection-eval:~:text=All%20metrics%20are%20computed%20allowing%20for%20at%20most%20100%20top%2Dscoring%20detections%20per%20image%20(across%20all%20categories)) by saying _"All metrics are computed allowing for at most 100 top-scoring detections per image (across all categories)."_ 
I also found the piece of code where this happens: [see here](https://github.com/ppwwyyxx/cocoapi/blob/4670067b35e7b65d618c9746c456fe2c1128049c/PythonAPI/pycocotools/cocoeval.py#L353-L371)

#### Notes:
- in my dataset, there is only 1 Ground Truth per image, therefore, the `gtId` & `image_id` are the same. But they do not have to be the same.
- For a detailed explanation of the attributes in COCOeval, please see the official code [here](https://github.com/ppwwyyxx/cocoapi/blob/4670067b35e7b65d618c9746c456fe2c1128049c/PythonAPI/pycocotools/cocoeval.py#L11-L51)

**Comment by collinmccarthy** [comment]
@rizavelioglu Thank you for taking the time to write this up!
